// <auto-generated />
using System;
using ClaimsModule.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimsModule.Persistence.Migrations
{
    [DbContext(typeof(ClaimsDbContext))]
    [Migration("20260928073939_AddGlPostingAuditBackstop")]
    partial class AddGlPostingAuditBackstop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimsModule.Domain.Audit.ClaimAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClaimId", "CreatedAt" }, "IX_ClaimAuditLog_ClaimId_CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "ClaimId", "EventType", "CreatedAt" }, "IX_ClaimAuditLog_ClaimId_EventType_CreatedAt");

                    b.HasIndex(new[] { "RelatedEntityId" }, "UX_ClaimAuditLog_RelatedEntityId_GlPostingSimulated")
                        .IsUnique()
                        .HasFilter("[EventType] = N'GL_POSTING_SIMULATED'");

                    b.ToTable("ClaimAuditLog", null, t =>
                        {
                            t.HasTrigger("TR_ClaimAuditLog_AppendOnly");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AssignedHandlerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ReportedDate")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("ReserveLimitOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ReserveLimitOverrideAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("ReserveLimitOverrideByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReserveLimitOverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedHandlerId");

                    b.HasIndex("PolicyId");

                    b.HasIndex(new[] { "OrganisationId", "Status", "UpdatedAt" }, "IX_Claims_OrganisationId_Status_UpdatedAt");

                    b.HasIndex(new[] { "OrganisationId", "ClaimNumber" }, "UX_Claims_OrganisationId_ClaimNumber")
                        .IsUnique();

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimParty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartyRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClaimId", "PartyRole", "IsActive" }, "IX_ClaimParties_ClaimId_PartyRole_IsActive");

                    b.ToTable("ClaimParties", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimRiskObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AssetDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssetReference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DamageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimRiskObjects", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimStatusTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystemOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MinimumRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresReason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FromStatus", "ToStatus" }, "UX_ClaimStatusTransitions_FromStatus_ToStatus")
                        .IsUnique();

                    b.ToTable("ClaimStatusTransitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("38a97a48-271f-4214-9db7-024d2e245127"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Draft",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = false,
                            ToStatus = "Open"
                        },
                        new
                        {
                            Id = new Guid("b99eafea-c240-4a77-bd3f-7c7e4ad40679"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = false,
                            ToStatus = "UnderInvestigation"
                        },
                        new
                        {
                            Id = new Guid("761b6cc3-850c-40d7-980e-a6bc8614946a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = false,
                            ToStatus = "PendingPayment"
                        },
                        new
                        {
                            Id = new Guid("b415c0c6-5358-44e1-9bad-f1d2ff3a43f3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = true,
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("ffe17aee-588f-469e-bedb-f4ea8903782f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Open",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = true,
                            ToStatus = "Withdrawn"
                        },
                        new
                        {
                            Id = new Guid("2543c201-57c1-4f59-bb00-4a7fcc32f36a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = false,
                            ToStatus = "Open"
                        },
                        new
                        {
                            Id = new Guid("c030fc17-dcb5-4848-9253-3364e3a7807e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = false,
                            ToStatus = "PendingPayment"
                        },
                        new
                        {
                            Id = new Guid("2849f2d3-700e-4713-92ad-8f12a457b94c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = true,
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("f7ff1102-bd41-4064-b11f-778d0181f00a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "UnderInvestigation",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = true,
                            ToStatus = "Withdrawn"
                        },
                        new
                        {
                            Id = new Guid("566f5ccb-82dd-4b28-a2bb-9210ce42b047"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "PendingPayment",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Handler",
                            RequiresReason = true,
                            ToStatus = "Closed"
                        },
                        new
                        {
                            Id = new Guid("28fbe2ff-696e-4100-a73e-66465a356dd1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Closed",
                            IsDeleted = false,
                            IsSystemOnly = false,
                            MinimumRole = "Supervisor",
                            RequiresReason = true,
                            ToStatus = "Reopened"
                        },
                        new
                        {
                            Id = new Guid("8cad141b-381d-4ffd-918c-83306c42a6d3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatus = "Reopened",
                            IsDeleted = false,
                            IsSystemOnly = true,
                            RequiresReason = false,
                            ToStatus = "Open"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimValidationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClaimId", "RuleCode" }, "UX_ClaimValidationIssues_ClaimId_RuleCode_Active")
                        .IsUnique()
                        .HasFilter("[Status] IN (N'Open', N'Acknowledged') AND [IsDeleted] = 0");

                    b.ToTable("ClaimValidationIssues", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.LossEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CauseOfLossCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal?>("EstimatedLossAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LossDate")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("LossDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LossLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PoliceReportNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ReportDate")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.HasIndex("OrganisationId", "CauseOfLossCode");

                    b.HasIndex(new[] { "LossDate" }, "IX_LossEvents_LossDate");

                    b.ToTable("LossEvents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Organisations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Demo Insurance Company"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Policies.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CoverageTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClientName" }, "IX_Policies_ClientName");

                    b.HasIndex(new[] { "OrganisationId", "PolicyNumber" }, "UX_Policies_OrganisationId_PolicyNumber")
                        .IsUnique();

                    b.ToTable("Policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8281fb25-5cd6-4f26-b82e-72695950beb3"),
                            ClientName = "Meridian Transport LLC",
                            CoverageTypes = "[\"Vehicle\",\"Cargo\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2024, 1, 1),
                            ExpirationDate = new DateOnly(2026, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PolicyNumber = "POL-2024-001001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("ae6abe22-49fa-4c63-950a-0e1022f61882"),
                            ClientName = "Harborview Properties Inc",
                            CoverageTypes = "[\"Property\",\"Liability\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2024, 6, 1),
                            ExpirationDate = new DateOnly(2026, 5, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PolicyNumber = "POL-2024-001002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("0276497d-199d-4d7a-b166-de5643601ae6"),
                            ClientName = "Coastal Builders Group",
                            CoverageTypes = "[\"Property\",\"Equipment\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2025, 3, 1),
                            ExpirationDate = new DateOnly(2027, 2, 28),
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PolicyNumber = "POL-2025-002001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("8ab0d13d-392d-47d9-91b6-d6c2088f2de0"),
                            ClientName = "Stanton Medical Group",
                            CoverageTypes = "[\"Liability\",\"Vehicle\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2025, 1, 1),
                            ExpirationDate = new DateOnly(2026, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PolicyNumber = "POL-2025-002002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("5fd883ac-3109-4539-af13-c387cef26942"),
                            ClientName = "Archived Corp",
                            CoverageTypes = "[\"Property\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2020, 1, 1),
                            ExpirationDate = new DateOnly(2021, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PolicyNumber = "POL-2023-000099",
                            Status = "Expired"
                        },
                        new
                        {
                            Id = new Guid("07516340-0391-4182-8b0d-4f507fad688b"),
                            ClientName = "Northwind Logistics Ltd",
                            CoverageTypes = "[\"Vehicle\",\"Cargo\",\"Liability\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2025, 1, 1),
                            ExpirationDate = new DateOnly(2030, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PolicyNumber = "POL-2025-003001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("95713a24-9905-4b0e-9d48-7518bb34be10"),
                            ClientName = "Summit Retail Holdings",
                            CoverageTypes = "[\"Property\",\"Liability\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2025, 1, 1),
                            ExpirationDate = new DateOnly(2030, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PolicyNumber = "POL-2025-003002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("07a6b67a-e72d-4535-bd39-d299b55e434f"),
                            ClientName = "Keystone Manufacturing Co",
                            CoverageTypes = "[\"Property\",\"Equipment\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EffectiveDate = new DateOnly(2025, 1, 1),
                            ExpirationDate = new DateOnly(2030, 12, 31),
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PolicyNumber = "POL-2025-003003",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.ReferenceData.CauseOfLossCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerilCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganisationId", "Code")
                        .HasName("AK_CauseOfLossCodes_OrganisationId_Code");

                    b.ToTable("CauseOfLossCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("997a4c70-15b9-49b4-9b50-210df0527a32"),
                            Code = "COL-FIRE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fire",
                            Notes = "Structure or contents fire",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Property",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("1a56ed19-8a6f-40f7-9bd4-f0e30d94b90f"),
                            Code = "COL-FLOOD",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Flood",
                            Notes = "Water intrusion from external source",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Weather",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("f6a7ba5c-0632-4907-bdc7-3d05d5705ee4"),
                            Code = "COL-THEFT",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Theft",
                            Notes = "Burglary, robbery, larceny",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Crime",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("4091c278-fbd1-4744-964e-910c77ba8430"),
                            Code = "COL-VEH-COL",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vehicle Collision",
                            Notes = "Impact with another vehicle or object",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Auto",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("84395762-ac14-4e68-bdad-afe906824b9b"),
                            Code = "COL-VEH-COMP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vehicle Comprehensive",
                            Notes = "Weather, theft, vandalism",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Auto",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("8d4d2ac8-35d2-4a3c-b034-1a690f2f9641"),
                            Code = "COL-LIAB",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Third Party Liability",
                            Notes = "Bodily injury or property damage to third party",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Liability",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = new Guid("3a6d297a-8cef-4352-9125-a7067f9244c0"),
                            Code = "COL-EQUIP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Equipment Breakdown",
                            Notes = "Mechanical or electrical failure",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Equipment",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = new Guid("997fa883-2560-4c33-8fb4-53aec3583554"),
                            Code = "COL-WIND",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Wind / Storm",
                            Notes = "Wind, hail, hurricane",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Weather",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = new Guid("98e9408f-6ee8-47b5-8319-3a240c46d516"),
                            Code = "COL-INJURY",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bodily Injury",
                            Notes = "Personal injury to claimant",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "Liability",
                            SortOrder = 90
                        },
                        new
                        {
                            Id = new Guid("e597f02e-2d9f-4687-91b4-c7a02bcc4ef3"),
                            Code = "COL-OTHER",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Other / Unknown",
                            Notes = "Catch-all for uncategorised losses",
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            PerilCategory = "General",
                            SortOrder = 100
                        });
                });

            modelBuilder.Entity("ClaimsModule.Domain.Reserves.ReserveComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LastChangeSequence")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVer")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClaimId", "Component" }, "UX_ClaimReserveComponents_ClaimId_Component")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ClaimReserveComponents", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Reserves.ReserveTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ChangeSequence")
                        .HasColumnType("int");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("ExceedsAggregateLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("NewBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostingJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostingStatus")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PreviousBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredAuthority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReserveComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ApprovalStatus", "PostingStatus", "ApprovedAt" }, "IX_ReserveHistory_ApprovalStatus_PostingStatus_ApprovedAt");

                    b.HasIndex(new[] { "ClaimId", "CreatedAt" }, "IX_ReserveHistory_ClaimId_CreatedAt");

                    b.HasIndex(new[] { "IdempotencyKey" }, "UX_ReserveHistory_IdempotencyKey")
                        .IsUnique();

                    b.HasIndex(new[] { "ReserveComponentId", "ChangeSequence" }, "UX_ReserveHistory_ReserveComponentId_ChangeSequence")
                        .IsUnique();

                    b.HasIndex(new[] { "ReserveComponentId" }, "UX_ReserveHistory_ReserveComponentId_Pending")
                        .IsUnique()
                        .HasFilter("[ApprovalStatus] = N'PendingApproval' AND [IsDeleted] = 0");

                    b.ToTable("ReserveHistory", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UserCreated")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserModified")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("415b998a-b77b-4d44-9a25-8f506dfd17e4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Alex Carter",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            Role = "Handler",
                            Username = "handler.alex"
                        },
                        new
                        {
                            Id = new Guid("6b870c3c-4333-441b-8c57-88f277f61fca"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Blake Jordan",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            Role = "Handler",
                            Username = "handler.blake"
                        },
                        new
                        {
                            Id = new Guid("7b2e441e-dc0b-42fc-8a8d-0b7e1308e1b8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Casey Morgan",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            Role = "Supervisor",
                            Username = "supervisor.casey"
                        },
                        new
                        {
                            Id = new Guid("cbbca2e1-4bd9-4714-9f79-735500e13c5d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Drew Taylor",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            Role = "Supervisor",
                            Username = "supervisor.drew"
                        },
                        new
                        {
                            Id = new Guid("c65a96eb-f89d-4a31-be62-eb79ea9343cf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Emery Brooks",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            Role = "Manager",
                            Username = "manager.emery"
                        },
                        new
                        {
                            Id = new Guid("3a97300c-8566-47a8-8e24-87ce3dae8759"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Finley Hayes",
                            IsActive = true,
                            IsDeleted = false,
                            OrganisationId = new Guid("b49c0515-77a9-49ff-be76-2a1fcfdc144f"),
                            Role = "Manager",
                            Username = "manager.finley"
                        });
                });

            modelBuilder.Entity("ClaimsModule.Persistence.ClaimNumbers.ClaimNumberCounter", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<int>("LastValue")
                        .HasColumnType("int");

                    b.HasKey("OrganisationId", "Year");

                    b.ToTable("ClaimNumberCounters", null, t =>
                        {
                            t.HasCheckConstraint("CK_ClaimNumberCounters_LastValue", "[LastValue] BETWEEN 1 AND 9999999");
                        });
                });

            modelBuilder.Entity("ClaimsModule.Persistence.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseLocation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_IdempotencyRecords_CreatedAt");

                    b.HasIndex(new[] { "UserId", "Key" }, "UX_IdempotencyRecords_UserId_Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Audit.ClaimAuditLog", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.Claim", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedHandlerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClaimsModule.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimsModule.Domain.Policies.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimDocument", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Claims.Claim", null)
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimParty", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Claims.Claim", null)
                        .WithMany("Parties")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimRiskObject", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Claims.Claim", null)
                        .WithMany("RiskObjects")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.ClaimValidationIssue", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Claims.Claim", null)
                        .WithMany("ValidationIssues")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.LossEvent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Claims.Claim", null)
                        .WithOne("LossEvent")
                        .HasForeignKey("ClaimsModule.Domain.Claims.LossEvent", "ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimsModule.Domain.ReferenceData.CauseOfLossCode", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId", "CauseOfLossCode")
                        .HasPrincipalKey("OrganisationId", "Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Policies.Policy", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.ReferenceData.CauseOfLossCode", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Reserves.ReserveComponent", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Claims.Claim", null)
                        .WithMany("ReserveComponents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Reserves.ReserveTransaction", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Claims.Claim", null)
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClaimsModule.Domain.Reserves.ReserveComponent", null)
                        .WithMany("Transactions")
                        .HasForeignKey("ReserveComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Users.User", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Persistence.ClaimNumbers.ClaimNumberCounter", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Persistence.Idempotency.IdempotencyRecord", b =>
                {
                    b.HasOne("ClaimsModule.Domain.Organisations.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ClaimsModule.Domain.Claims.Claim", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LossEvent")
                        .IsRequired();

                    b.Navigation("Parties");

                    b.Navigation("ReserveComponents");

                    b.Navigation("RiskObjects");

                    b.Navigation("ValidationIssues");
                });

            modelBuilder.Entity("ClaimsModule.Domain.Reserves.ReserveComponent", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
